### ISSUE TITLE
any doc or guide to use it?

### ISSUE THREAD

**Issue by andyyuan78** [bmoscon/StreamingAlgorithms#17]

**Comment by bmoscon** [comment]
Most of them have sample programs that show how they are used. Basically just include the header file (assuming you're interested in the c++ variations) and use the class. If there is a specific one you have a question about I can provide more detail. I can also modify it to provide static and shared libraries if thats useful.

**Comment by bmoscon** [comment]
no update from OP about what he wanted specifically. closing
