### ISSUE TITLE
StreamSummary - save and load for consistency

### ISSUE THREAD

**Issue by drdhaval2785** [bmoscon/StreamingAlgorithms#19]
I love python implementation of StreamSummary.
StreamSummary is usually done on incremental data.
e.g.
In my case, I am doing topK page views analysis via this StreamSummary code on google analytics of let's say past 1 month.
Now tomorrow I get a data of pageviews of tomorrow, I should be able to incrementally apply the script.

Please incorporate the save and load methods in the class.

save can save the necessary parameters and values in JSON.
load can reconstruct bucket and StreamSummary object from the loaded JSON.
This way, we can use it for incremental training.

Thanks

**Comment by bmoscon** [comment]
Will do, hopefully tomorrow

**Comment by drdhaval2785** [comment]
Thank you for your precious time.

**Comment by bmoscon** [comment]
fixed with latest commit. usage is via save / load methods. eg:

```python
d = s.save()
d
>>> {1: ['d', 'e'], 2: ['f', 'g'], 3: ['a']}
s.load(d)
```
