### ISSUE TITLE
StreamSummary - str representation

### ISSUE THREAD

**Issue by drdhaval2785** [bmoscon/StreamingAlgorithms#20]
The string representation __str as of now gives bucket number and members in that bucket.
Bucket number is not much of importance.

Please modify it to show 
Bucket counter (instead of or in addition to) bucket number.

This way the user can know the counter of most frequently occurring items.

**Comment by bmoscon** [comment]
Will address this at the same time I address #19 

thanks for the suggestions!

**Comment by bmoscon** [comment]
After looking over the code - the bucket number is the counter, so I'm not sure what you mean.

If you mean the ACTUAL count, i.e. the actual number of times an element has been seen, then I think you have mistaken something about the algorithm and I'd suggest you read over the paper this is based on. This only keeps track of the top k elements in a stream, but it isnt possible to accurately keep track of a number of times something has been seen. The value of the bucket is the "count" with respect to the algorithm, but its not accurate in regards to actual times that item has been seen.

**Comment by drdhaval2785** [comment]
Yes. After raising the issue, I also felt that I missed out the crux of
algorithm. Sorry for false alarm. It is not possible to have actual counter
of each member in streamsummary. Close the issue please.
